sbx421_block.c:
	gcc sbx421_block.c -o sbx421_block.o

sbx421_unblock.c:
	gcc sbx421_unblock.c -o sbx421_unblock.o

sbx421_count.c:
	gcc -o sbx421_count sbx421_count.c

sbx421_run.c:
	gcc -o sbx421_run sbx421_run.c
